### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#1]
trying an old-new comparison, and I get an error.

https://github.com/bpbond/nmrrr/blob/12819e9c0d015fd5a192060962e764f1fa96949d/tests/testthat/test-processing.R#L3-L13

![image](https://user-images.githubusercontent.com/50244730/129460315-0b1cc576-9828-4f9e-a0fe-fc95f86d8ead.png)

@bpbond

**Comment by bpbond** [comment]
Looks like the error is occurring in the `set_bins` call, not any of the testthat routines.

**Comment by kaizadp** [comment]
Not sure what's causing it. 

You're right, I think the error begins with the `set_bins` call, but I can't figure it out. The function itself works when I run it outside of the testthat routine.


I thought maybe it was the pipes, so I tried to break it down without pipes. But same error. 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/50244730/129600745-74eb7eb0-ea24-4fe0-9648-c3d939dff0c3.png">

My recent commits are also causing the CMD-checks to fail. Probably related.
4baeebe

**Comment by bpbond** [comment]
Is this pushed to a branch? I can take a look.

**Comment by kaizadp** [comment]
Pushed to the main branch

**Comment by bpbond** [comment]
The error is happening because when tests are run, the working directory is `tests/testthat`, not the package root. You need to account for this—either change the call to `set_bins`, or create a `tests/testthat/bins/` subdirectory.

**Comment by kaizadp** [comment]
Yes! That fixed the testthat issue. c5fb420 a6d7a99.

Then: 
- The `hello()` function was throwing an error in CMD-check, so I deleted it. 4a5c139.

- `@examples` in the `set_bins()` also gave me an error in CMD-check, so I deleted that. 1d2584f.

R-CMD-check now passes (yay). but I'll need your help fixing the `@examples` issue.

**Comment by bpbond** [comment]
Great!
