### ISSUE TITLE
data acquired from different programs

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#3]
@bpbond 

There are two major NMR programs, TopSpin and MestreNova (MNova), and we'd like our functions to be able to handle data from both. The problem - the data are in very different formats (see screenshots below). The way I see it, we have two options:

1. one single function (`import_spectra`, `import_peaks`, etc.) that takes into account the various formats. Maybe a kind of `if_loop` where the user enters the software name? If software == MNova, then do x. If software == TopSpin, then do y.
2. separate functions for each program (`import_spectra_topspin`, `import_spectra_mnova`)

Thoughts? 

### Spectra Files

TOPSPIN - spectra
![image](https://user-images.githubusercontent.com/50244730/153644318-1de1eac2-932b-407e-bab5-cf9adcf29e84.png)

MNOVA - spectra
<img width="192" alt="image" src="https://user-images.githubusercontent.com/50244730/153644206-97d205b8-2946-408c-880a-1638ed8fae60.png">

### Peaks Files

TOPSPIN - peaks
![image](https://user-images.githubusercontent.com/50244730/153643779-33d7603b-9be0-43c8-818f-5c0540b5ec39.png)

MNOVA - peaks, version 1
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/50244730/153645443-27fa0663-ee81-4b84-9bd9-0209a5a326c9.png">

MNOVA - peaks, version 2
![image](https://user-images.githubusercontent.com/50244730/153643932-4a68acaf-d252-42d4-b72d-89e1f98b09c3.png)

**Comment by bpbond** [comment]
I would suggest that there's a single function that automatically determines which format the file is in and handles it accordingly. We'd also provide a way for users to override this. For example:
```r
import_nmr_spectra_data <- function(filename, type = "auto")) {
  if(type != "auto") {
    # user is overriding
  } else {
    # auto-sense file type
  }
  # proceed, now that file type is determined
  # probably only the file-read step will differ between types, 
   # and everything else will be identical?
}
```

**Comment by bpbond** [comment]
The auto-sense step will do something like
1. Use `readLines(n = 3)` to read in the beginning of the file
2. If starts with a blank line and then four CSV-style columns, it's TOPSPIN
3. If a single column only, it's MNOVA
4. Otherwise, error: unknown file type

**Comment by kaizadp** [comment]
ok, that's helpful. I don't know how to do the auto-sense, so I have set conditions for `METHOD == xxx`. would you be able to convert that into the auto-detect conditions?

**spectra**
https://github.com/bpbond/nmrrr/blob/2627d7b91c23df70742a13454985a19653a8d60d/R/1-functions_processing.R#L94


**peaks**
https://github.com/bpbond/nmrrr/blob/2627d7b91c23df70742a13454985a19653a8d60d/R/1-functions_processing.R#L218

**Comment by bpbond** [comment]
Could you provide sample files for each format please?

**Comment by bpbond** [comment]
Basically, though, it will look something like this:
```r
filestart <- readLines(filename, n = 2)  # read the first two lines
if(filestart[1] == "" && length(grep(",", filestart))) {
  # if line 1 is blank and line 2 has commas, should be TOPSPIN
} else {
  # should be MNOVA
}

**Comment by kaizadp** [comment]
Sample files are here. Folders labelled by the method I've been using (mnova, topspin, single column, multiple column).
I have been using these for the code development.
https://github.com/bpbond/nmrrr/tree/master/inst/extdata

I also have a separate R file here that's not part of the package, to experiment and play with the code on the side:
https://github.com/bpbond/nmrrr/blob/master/scratchpad.R

Thanks!
