### ISSUE TITLE
nmr_plot_spectra parameter names

### ISSUE THREAD

**Issue by bpbond** [kaizadp/nmrrr#39]
```
nmr_plot_spectra <- function(dat, BINSET, LABEL_POSITION, mapping, STAGGER) {
```

The all-caps BINSET, LABEL_POSITION, and STAGGER are jarring and inconsistent with the naming convention used by the rest of the package functions. Could we change them?

**Comment by kaizadp** [comment]
yes, definitely!

**Comment by kaizadp** [comment]
would you like me to make those changes? Happy to.

**Comment by bpbond** [comment]
👋  If you don't mind!

**Comment by kaizadp** [comment]
Of course! Just didn’t want us duplicating efforts.
