### ISSUE TITLE
Checking vignettes and vignette input files

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#47]
@bpbond 

1. I've written the three vignettes, could you please review to make sure they look ok, and that I'm not missing anything? I'll also ask AMP and MEB to check the content of the vignettes. Two of the vignettes contain only text, no code running. The `nmrrr` vignette walks the user through the workflow.  

2. Suggestions on vignette titles? I currently have this, but I'm not sure how these will be saved in the package, or how to call the vignette in R (e.g. `vignette("nmrrr_binsets")` or `vignette("Bin sets included with nmrrr")`).
https://github.com/bpbond/nmrrr/blob/84d4d14dfcc9a0278a209ace7eb400591a806f5b/vignettes/nmrrr_binsets.Rmd#L2-L5

4. I'm having some trouble with the file paths in the `nmrrr` vignette. The "folder/file" format gave me a CMD error, so I switched to the system.file("folder", "file") format, and CMD check passed. But when I try to knit the .Rmd, it gives me an error.  

https://github.com/bpbond/nmrrr/blob/84d4d14dfcc9a0278a209ace7eb400591a806f5b/vignettes/nmrrr.Rmd#L59-L66

![image](https://user-images.githubusercontent.com/50244730/218214359-3cd4e58f-fe4f-4e91-a00d-8cda41834e18.png)

**Comment by bpbond** [comment]
@kaizadp 

See PR https://github.com/bpbond/nmrrr/pull/48. Further thoughts:

1. I'm not sure it's worth it (imho) to have text vignettes documenting the datasets; these are _already_ documented via R's help system, and now they're documented again here, which doubles your work (have to keep all this consistent, etc)
2. To open the vignettes use `browseVignettes()` or `vignette("nmrrrr")`
3. The file paths work fine for me, and the vignette builds no problem. You definitely do want to use `system.file`

I hope this is useful! Happy to discuss more if useful. Nice job on this!
