### ISSUE TITLE
final (?) push!

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#50]
for @kaizadp:
- [x] check ~~Preson and Baldock~~ Baldock2004 bins from AMP
- [x] check CadeMenun bins from MEB
- [x] check names for all datasets and bins
- [x] add contexts to bins
- [x] delete `old` directory when we're done with everything
- [x] startup message (`R/zzz.R`)
- [ ] Wiki info for MNova and initial processing (see [here](https://github.com/kaizadp/nmrrr/wiki))

for @bpbond:
- [x] final checks on package, documentation, etc.
- [x] vignette:
    - [x] review vignette, please
    - [x] vignette: we provide one example (kfp_hysteresis) that is run (eval = TRUE) in the markdown, and one example (amp_ss) where we just provide the workflow, but don't actually run it (eval = FALSE). the latter is mainly because the initial processing is in tidyverse and I didn't want to deal with converting to base-R. Is this ok? (PS - we also include both examples in our manuscript)
    - [x] sessionInfo for vignette: yay or nay?
    - [x] I've installed and loaded the package, but am unable to access the vignette through `vignette("nmrrr")` or `browseVignettes("nmrrr")`
- [x] there is currently no documentation for the datasets in `inst/extdata`. is this ok?
- [x] should we set up a GitHub Pages for this package? or just stick with a GitHub wiki?

--- 

finally,
- [ ] submit to CRAN!

**Comment by bpbond** [comment]
Hi @kaizadp the vignette looks good! I really like the way you clearly describe the datasets at the beginning of each example.
* Yes, I think one run example and one not-run example (for good reasons) is fine
* I don't see the need for `sessionInfo()` in this case
* Execute `devtools::install(build_vignettes = TRUE)` on the console to ensure vignettes installed with package

>no documentation for the datasets in inst/extdata

Good question! I think so? They're not intended to be user-accessible except for learning via the vignettes, right? It's the bin documentation that is critical (and done) I think.

I don't think GitHub Pages is needed right now. You have other things on your plate 😄

**Comment by bpbond** [comment]
Two more checkboxes before submission, for your consideration:

- [x] Transfer repo to `kaizadp/nmrrr` 
- [x] Reformat the code for consistency and clarity using the [styler](https://www.tidyverse.org/blog/2017/12/styler-1.0.0/) package

**Comment by kaizadp** [comment]
> Transfer repo to kaizadp/nmrrr

There already is stuff at https://github.com/kaizadp/nmrrr. Should I move that to a separate branch and keep it in the same repo, or should I just rename it to something else (`kaizadp/nmrrr-workflow`) so we have a fresh and clean repo for this package?


>  delete old directory when we're done with everything

There are some datasets [here](https://github.com/bpbond/nmrrr/tree/master/old/extdata_large_files), which were too large for the package, but we'd considered leaving them in the repo for people to access/play with if needed. 
1. yay or nay?
2. if yay, how do we save them on the repo? any specific directory name we should use?

**Comment by bpbond** [comment]
I think we want to `git remote rm upstream` (to detach `bpbond/nmrrr` from your upstream repo), delete `kaizadp/nmrrr`, and then transfer. Obviously before doing so, make sure we both have up-to-date local files in case something goes wrong!

If the datasets are useful, okay! I don't have a specific name; your `old/...` choice works fine imho.

**Comment by bpbond** [comment]
- [x] Update `Version: 0.1.0` in DESCRIPTION file (if you want to do so)

**Comment by bpbond** [comment]
Consider whether we want to transfer the repo to https://github.com/kaizadp/nmrrr or to https://github.com/COMPASS-DOE/nmrrr.  🤷

**Comment by kaizadp** [comment]
These are the two notes. 

For the first one, I’ll just delete the larger_datasets directory when submitting to CRAN. That directory is just for the GitHub repo. 

Not sure how to handle the second one.

![image](https://user-images.githubusercontent.com/50244730/232838155-2611e058-cddb-4da2-a074-750d3d7f2fa9.png)

**Comment by kaizadp** [comment]
- [x] kfp: rename function files
