### ISSUE TITLE
setting defaults for graph function?

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#51]
@bpbond 

https://github.com/kaizadp/nmrrr/blob/afef424b81aa042615b6f55e97b0065f13c5122e/R/1-functions_graphs.R#L30

Thoughts on setting some default values for the graphing function? Just so it prints the graph with minimal input, and then users can modify the parameters as needed. Right now, the function won't run unless we provide *five* inputs.

`nmr_plot_spectra <- function(dat, binset, label_position = 100, mapping = aes(x = ppm, y = intensity), stagger = 10) {`

^ these defaults gives me this graph for my kfp_hysteresis data. Not very pretty, but it at least gives me a graph, which I can then modify. 

![image](https://user-images.githubusercontent.com/50244730/232849834-48f0bb19-0b97-436a-95c8-16052abfa986.png)

**Comment by bpbond** [comment]
Those defaults seem reasonable; any reason _not_ to do it this way?

**Comment by kaizadp** [comment]
Nope, just checking that I'm not breaking some unspoken rules of function-building!

**Comment by kaizadp** [comment]
Of course, some datasets will have intensities in the order of 10^6, so these defaults won't look as good - but this is meant to be just a starting point, so users know how to adjust their parameters. Otherwise, they need to sift through the dataset to try and guess what works. 

ok, setting these defaults!

**Comment by kaizadp** [comment]
these defaults gave me a new NOTE: 

```
no visible binding for global variable `ppm`
no visible binding for global variable ‘intensity’
```

So I added utils::globalVariables() to `R/utils.R` b395893. is this an ok place for that, or should I make a new file?

**Comment by bpbond** [comment]
Yes, that's fine I think!
