### ISSUE TITLE
checks

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#52]
@bpbond 

Three notes in the most recent CMD check

1. size of tarball
This is probably because of the `larger_datasets` directory. This is staying only on the GitHub repo, so I will delete before I submit to CRAN. Not an issue.

2. non-standard directory found
same as above. Not an issue.

3. "use inherits() ..."
Need help, please. Not sure what the right syntax is for this.

![image](https://user-images.githubusercontent.com/50244730/233171490-d2a92e20-674b-4015-b377-a4fbba154f4a.png)

https://github.com/kaizadp/nmrrr/actions/runs/4735866927/jobs/8406649483

**Comment by bpbond** [comment]
Hi @kaizadp the only issue I see when checking the package is the non-standard file/directory one.

This is easy to fix--you just need to tell R to ignore `larger_datasets`. Add the following line to `.Rbuildignore`:
```
^larger_datasets/
```

Once this is done I get

<img width="358" alt="Screen Shot 2023-04-19 at 3 21 25 PM" src="https://user-images.githubusercontent.com/1956468/233178603-e2e1f25b-709b-4c2e-9a35-da51ec330549.png">

Woot!! 🎉

**Comment by bpbond** [comment]
P.S. this should take care of 1 and 2 above. 3 is weird, don't know but let me know if you keep seeing it.

**Comment by kaizadp** [comment]
Yay, fixed 1 and 2. Still getting 3 though

![image](https://user-images.githubusercontent.com/50244730/233183021-5a254fae-5025-4790-87c0-5b5859f13fee.png)

**Comment by bpbond** [comment]
Oh, sorry, I should have looked more closely earlier. I don't know why this is occurring on your system and not mine, but the issue is that we're comparing an output of `class` directly to a string, which isn't great. Change to 
```r
if (inherits(mapping, "uneval")) {
```

**Comment by bpbond** [comment]
☝️  in line 31 of `1-functions_graphs.R`

**Comment by kaizadp** [comment]
Done! I had to change it to `inherits(class(mapping, ...)`. That then screwed up the test-plotting.R, so I updated that.

8d52783d498fbeea44287b7c4cdbd43a1cf72cc9


![image](https://user-images.githubusercontent.com/50244730/233197041-40cd8579-d813-4d9b-9b3d-42bbf7dcce84.png)

**Comment by kaizadp** [comment]
![alt](https://media.giphy.com/media/Yvk01MEG2Mxe168yxw/giphy.gif)

**Comment by bpbond** [comment]
YEEAAAAAHHHH 🏆
