### ISSUE TITLE
testing data

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#6]
Three potential datasets:

1. kfp_hysteresis
2. amp_tempest
3. meb_incubations  

**kfp_hysteresis:**
- [x] corekey
- [x] spectra data
- [x] peaks data - multi-column

**amp_tempest:**
- [ ] corekey
- [x] spectra data
- [x] peaks data - single column

**meb_incubation:**
- [x] corekey
- [x] spectra data
- [x] peaks data - single column, but different format

**Comment by bpbond** [comment]
See #15 - let's discuss

**Comment by bpbond** [comment]
For _test data_ I have simplified to

* peaks_mnova_multiple
* peaks_single
* peaks_topspin
* spectra

Each of these directories (inside of `tests/testthat/compdata/` has a README file noting which dataset the files are from.
