### ISSUE TITLE
different programs and file types

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr#9]
@bpbond 

Cleaning of NMR spectra: 
- baseline correction, phase correction, peak deconvolution, etc.
- this is done manually and individually per sample using specific NMR software (MestreNova/MNova and Topspin)
- NOT part of this package

Processing and analysis of NMR spectra/data (using `nmrrr` package):
- take output from MNova or Topspin (.csv files) and process them using the package
- there are two categories of files: spectra files and peaks files
- see attached chart for different types/formats, and functions used to process them. (PDF as well as PNG versions)

[nmrrr_file_structure.pdf](https://github.com/bpbond/nmrrr/files/9378034/nmrrr_file_structure.pdf)

![nmrrr_file_structure](https://user-images.githubusercontent.com/50244730/185505835-6a5f7f54-5130-458c-b1ed-8fb9a7ab1e07.png)

**Comment by bpbond** [comment]
☝️ this material should go in a vignette!

**Comment by kaizadp** [comment]
^ being added to the appendix of the manuscript
